name: eto
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - beautifulsoup4=4.9.3
  - boto3=1.16.9
  - findspark=1.3.0
  - ipywidgets=7.5.1
  - jinja2=2.11.2
  - jupyter_contrib_nbextensions=0.5.1
  - jupyterlab=2.2.9
  - magma-cuda110
  - matplotlib=3.3.2
  - nbconvert=6.0.7
  - nodejs=14.14.0
  - numpy=1.19.2
  - opencv=4.5.0
  - pandas=1.1.4
  - pexpect=4.8.0
  - pillow=8.0.1
  - pip=20.2.4
  - psycopg2=2.8.6
  - pyarrow=2.0.0
  - pyspark=3.0.1
  - pytest=6.1.2
  - python=3.7.8
  - python-snappy=0.5.4
  - pytorch=1.7.0
  - requests=2.24.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - setuptools=49.6.0
  - sqlalchemy=1.3.20
  - sqlite=3.33.0
  - tini=0.18.0
  - torchvision=0.8.1
  - widgetsnbextension=3.5.1
