name: Contrib

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ros:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Checkout LFS objects
        run: git lfs pull
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: sbt install
        run: |
          git reset --hard HEAD && sbt publishLocal
      - name: Install Dependencies
        working-directory: python
        run: |
          python -m pip install -q --use-feature=in-tree-build . wheel
      - name: Install rikai-ros
        working-directory: contrib/ros
        run: |
          python -m pip install --extra-index-url https://rospypi.github.io/simple/ --use-feature=in-tree-build .[dev]
      - name: Test rikai-ros
        working-directory: contrib/ros
        run: pytest
  yolov5:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Checkout LFS objects
        run: git lfs pull
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: sbt install
        run: |
          git reset --hard HEAD && sbt publishLocal
      - name: Install Rikai
        working-directory: python
        run: |
          python -m pip install -q --use-feature=in-tree-build . wheel
      - name: Install rikai-yolov5
        working-directory: contrib/yolov5
        run: |
          python -m pip install --use-feature=in-tree-build .[dev]
      - name: Test rikai-yolov5
        working-directory: contrib/yolov5
        run: pytest
  coco:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Checkout LFS objects
        run: git lfs pull
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: sbt install
        run: |
          git reset --hard HEAD && sbt publishLocal
      - name: Install Dependencies
        working-directory: python
        run: |
          python -m pip install -q --use-feature=in-tree-build . wheel pycocotools
      - name: Install rikai-coco
        working-directory: contrib/coco
        run: |
          python -m pip install --use-feature=in-tree-build .[dev]
      - name: Test rikai-coco
        working-directory: contrib/coco
        run: pytest
