name: Python

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.8] # TODO add 3.7, 3.9 after test
        scala-version: [ 2.12.10, 2.13.7 ]
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        lfs: true
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.11
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ matrix.scala-version }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: sbt install
      run: |
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
        echo "SCALA_VERSION=${{matrix.scala-version}}" >> $GITHUB_ENV
        sbt ++${{matrix.scala-version}} publishLocal
    - name: Start docker-compose
      run: |
        docker-compose -f .github/docker-compose.yml up -d
    - name: cache pip
      uses: actions/cache@v2
      with:
        path: /opt/hostedtoolcache/rikai/${{ matrix.python-version }}
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: apt update and install
      run: |
        sudo apt update
        sudo apt-get -y -qq install libsnappy-dev ffmpeg
    - name: Pip install
      working-directory: python
      run: |
        PYTHONUSERBASE=/opt/hostedtoolcache/rikai/${{ matrix.python-version }} \
        python -m pip install --user -e .[all,dev]
    - name: Run python tests
      working-directory: python
      run: |
        pip install pytest
        PYTHONUSERBASE=/opt/hostedtoolcache/rikai/${{ matrix.python-version }} pytest -x -v --durations=10 --ignore=tests/parquet/internal
      env:
        SPARK_LOCAL_IP: "127.0.0.1"
        TEST_MLFLOW_TRACKING_URI: "http://localhost:15000"
  mac-build:
    runs-on: macos-11
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.11
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Test Pip install
      working-directory: python
      run: |
        python -m pip install -q wheel
        python setup.py bdist_wheel
        python -m pip install $(ls dist/rikai*.whl)
